Cartão de Crédito Cielo
<br /><br />
<?php
	
	
	if($_info = $this->getInfo())
	{
		if($_info->getOrder())
		{
			$payment = $_info->getOrder()->getPayment();
			
			if($payment->getAdditionalInformation ('Cielo_error'))
			{
				echo "Erro na transação: " . $payment->getAdditionalInformation ('Cielo_error');
			}
			else
			{
				$tid = $payment->getAdditionalInformation ('Cielo_tid');
				$status = $payment->getAdditionalInformation ('Cielo_status');
				$cardType = $payment->getAdditionalInformation ('Cielo_cardType');
				$installments = $payment->getAdditionalInformation ('Cielo_installments');
				
				$allCards = Mage::getModel('Maxima_Cielo/cc_types')->toArray();
				$cardType = $allCards[$cardType];
				$installments = ($installments == 1) ? '&#192; vista' : $installments . " vezes";
				
				$html = "<b>ID Transação</b>: " . $tid . "<br />";
				$html .= "<b>Status</b>: " . Mage::helper('Maxima_Cielo')->getStatusMessage($status) . "<br />";
				$html .= "<b>Bandeira</b>: " . $cardType . "<br />";
				$html .= "<b>Parcelamento</b>: " . $installments . "<br /><br />";
				
				echo $html;
			}
		}
	}
?>