Cartão de Crédito Cielo
<br /><br />
<?php
	
	
	if($_info = $this->getInfo())
	{
		if($_info->getOrder())
		{
			$payment = $_info->getOrder()->getPayment();
			
			if($payment->getAdditionalInformation ('Cielo_error'))
			{
				echo "Erro na transação";
			}
			else
			{
				$tid = $payment->getAdditionalInformation ('Cielo_tid');
				$status = $payment->getAdditionalInformation ('Cielo_status');
				
				$html  = "<b>ID Transação</b>: " . $tid . "<br />";
				$html .= "<b>Status</b>: ";
				
				// possiveis status 
				// -1 nao foi possivel consultar
				// 0 criada
				// 1 em andamento
				// 2 autenticada
				// 3 nao autenticada
				// 4 autorizada ou pendente de captura
				// 5 nao autorizada
				// 6 capturada
				// 8 nao capturada
				// 9 cancelada
				// 10 em autenticacao
				
				$html .= Mage::helper('Maxima_Cielo')->getStatusMessage($status);
				
				echo $html;
			}
		}
	}
?>