<br />
<fieldset class="form-list">
	<ul id="payment_form_Maxima_Cielo_Cc" style="display:none;">

<?php
	
	$cardsData = $this->getAllowedCards();
	
	$size = count($cardsData);
	
	for($i = 0; $i < $size; $i++)
	{
		$value = $cardsData[$i]['value'];
		$label = $cardsData[$i]['label'];
		$img = $this->getSkinUrl() . "images/cielo/" . $cardsData[$i]['image'];
		
		// abre agrupamento de bandeiras
		if($i % 3 == 0)
		{
?>
		<li class="first">
		<ul class="card-logo">
<?php
		}
		
		// bandeira em questao
?>
			<li style="width: 30%; float: left;">
				<label for="card-<?php echo $value; ?>"><img src="<?php echo $img; ?>" title="<?php echo $label; ?>"><br>
					<input name="payment[cc_type]" type="radio" value="<?php echo $value; ?>" id="card-<?php echo $value; ?>" class="validate-one-required-by-name" />
				</label>
			</li>
<?php
		// fecha agrupamento de bandeiras
		if(($i == $size - 1) || ($i + 1 % 3 == 0))
		{
?>
		</li>
		</ul>
<?php
		}
	}	
?>
		
		<li>
			<br />
			<label for="Maxima_Cielo_parcelas"><?php echo $this->__('Installments') ?> </label><br />
			<div class="input-box">
				<select id="Maxima_Cielo_parcelas" name="payment[parcels_number]">
					<?php foreach($this->getInstallments() as $parcel): ?>
					<option value="<?php echo $parcel['num'] ?>"><?php echo $parcel['label'] ?></option>
					<?php endforeach ?>
				</select>
			</div>
		</li>
	</ul>
</fieldset>
<br />