<fieldset class="form-list">
	<ul id="payment_form_Maxima_Cielo_Dc" style="display:none;">
		<li class="first">
			<br>
			<ul class="card-logo">

				<li style="width: 20%; float: left;">
					<label for="card-VI"><img src="<?php echo $this->getSkinUrl(); ?>images/cielo/Visa-Electron.png"><br>
						<input name="payment[cc_type]" type="radio" value="visa" id="cielo_cc_type" class="validate-one-required-by-name">
					</label>
				</li>
				
				<li style="width: 20%; float: left;">
					<label for="card-MC"><img src="<?php echo $this->getSkinUrl(); ?>images/cielo/Master.png"><br>
						<input name="payment[cc_type]" type="radio" value="mastercard" id="cielo_cc_type" class="validate-one-required-by-name">
					</label>
				</li>
				
			</ul>
		</li>
		<br />
	</ul>
</fieldset>
